packages/fulcrum-website/_includes/footer.html, packages/fulcrum-website/_includes/header.html, packages/fulcrum-website/_includes/svg/sai.svg, packages/fulcrum-website/_sass/component/_flex.scss, packages/fulcrum-website/_sass/component/_sections.scss, packages/fulcrum-website/assets/js/lending.js, packages/fulcrum-website/assets/js/main.js, packages/fulcrum-website/assets/js/trading.js, packages/fulcrum-website/index.md, packages/fulcrum-website/lending.md
- Add TVL block to trade page (instead of trading stats)
- Remove BAT, REP. Add SAI instead.
- Dynamic font size at calculator widget result ($/month)
- Live earnings counter updates every 10ms
=> Fulcrum website edits

packages/fulcrum/package.json, packages/fulcrum/src/assets/abi-gen-templates/partials/call.handlebars, packages/fulcrum/src/assets/abi-gen-templates/partials/tx.handlebars, packages/fulcrum/src/components/OwnTokenGridRow.tsx, packages/fulcrum/src/components/TradeTokenGridRow.tsx, packages/fulcrum/src/contracts/DAppHelper.ts, packages/fulcrum/src/contracts/iTokenContract.ts, packages/fulcrum/src/contracts/oracle.ts, packages/fulcrum/src/contracts/pTokenContract.ts, packages/fulcrum/src/domain/Web3ConnectionFactory.ts, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/tsconfig.json, packages/fulcrum/tslint.json, packages/torque/package.json, packages/torque/src/assets/images/error_icon.svg, packages/torque/src/components/ManageCollateralFormWeb3.tsx, packages/torque/src/components/WalletTypeSelector.tsx, packages/torque/src/contracts/iBZxContract.ts, packages/torque/src/contracts/iTokenContract.ts, packages/torque/src/contracts/oracle.ts, packages/torque/src/domain/Web3ConnectionFactory.ts, packages/torque/src/pages/DashboardPage.tsx, packages/torque/src/services/TorqueProvider.ts, packages/torque/src/styles/components/manage-collateral-form.mobile.scss, packages/torque/src/styles/components/manage-collateral-form.scss, packages/torque/src/styles/components/wallet-type-selector.scss, yarn.lock
- Restricted manage collateral slider's minValue to prevent withdraw 
- Disabled END setup for nonWeb3 wallets 
- Hid nonWeb3 wallets block
=> Torque withdraw restrictions

packages/torque/src/assets/images/error_icon.svg, packages/torque/src/components/ManageCollateralFormWeb3.tsx, packages/torque/src/styles/components/manage-collateral-form.mobile.scss, packages/torque/src/styles/components/manage-collateral-form.scss
Revert "Disable manage collateral withdraw by restricting slider's min value"
This reverts commit 0142e3b9960b38c79c606366cd5b34d150d67848.
=> Torque: Allow users to withdraw

packages/fulcrum/src/components/OnChainIndicator.tsx
Solves https://trello.com/c/IFgwLfDR/59-fulcrum-wallet-selector-popup
=> Increase wallet-popup's clickable area

packages/fulcrum/src/components/LendForm.tsx, packages/fulcrum/src/components/TradeForm.tsx
Add step="any" to input type="number"
=> Fulcrum: fix "Enter a valid value" mobile Lend/Trade form error

packages/fulcrum-website/_sass/component/_sections.scss, packages/fulcrum-website/_sass/component/_spacing.scss, packages/fulcrum-website/_sass/component/_typography.scss, packages/fulcrum-website/lending.md
https://trello.com/c/AX392vG6/62-fulcrum-apr-label-at-lending-page
=> Update label apr

packages/fulcrum/src/components/AppRouter.tsx, packages/fulcrum/src/components/InfoBlock.tsx, packages/fulcrum/src/components/RiskDisclosure.tsx, packages/fulcrum/src/layout/Footer.tsx, packages/fulcrum/src/layout/FooterMenu.tsx, packages/fulcrum/src/layout/HeaderOps.tsx, packages/fulcrum/src/pages/HomePage.tsx, packages/fulcrum/src/pages/LandingPage.tsx, packages/fulcrum/src/pages/LendPage.tsx, packages/fulcrum/src/pages/StatsPage.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/styles/base/_modal.scss, packages/fulcrum/src/styles/components/info-block.scss, packages/fulcrum/src/styles/components/lend-form.scss, packages/fulcrum/src/styles/components/risk-disclosure.scss, packages/fulcrum/src/styles/index.scss, packages/fulcrum/src/styles/layout/_footer.scss
https://trello.com/c/Z6MWDnL4/63-fulcrum-defi-risk-disclosure
=> DeFi risk disclosure

packages/torque/src/assets/images/ic__close.svg, packages/torque/src/components/AppRouter.tsx, packages/torque/src/components/InfoBlock.tsx, packages/torque/src/components/RiskDisclosure.tsx, packages/torque/src/layout/Footer.tsx, packages/torque/src/layout/FooterMenu.tsx, packages/torque/src/layout/HeaderOps.tsx, packages/torque/src/pages/BorrowPage.tsx, packages/torque/src/pages/DashboardPage.tsx, packages/torque/src/pages/LandingPage.tsx, packages/torque/src/pages/LandingPageStatic.tsx, packages/torque/src/pages/WalletSelectionPage.tsx, packages/torque/src/styles/base/_utilities.scss, packages/torque/src/styles/components/info-block.scss, packages/torque/src/styles/components/risk-disclosure.scss, packages/torque/src/styles/index.scss, packages/torque/src/styles/layout/_footer.scss
https://trello.com/c/RZz0xNOA/65-torque-welcome-message-with-risk-disclosure
=> Torque risk disclosure

.github/workflows/bzx-api-rsync.yml
This reverts commit 14428499de565f406395a8a084d51f7faf1b0f25.
=> Revert "Update bzx-api-rsync.yml"

packages/fulcrum-website/_data/products.json, packages/fulcrum-website/_sass/component/_typography.scss, packages/fulcrum-website/assets/js/lending.js, packages/fulcrum-website/assets/js/main.js, packages/fulcrum-website/assets/js/trading.js, packages/fulcrum-website/index.md, packages/fulcrum-website/lending.md
https://trello.com/c/zig57syj/74-bzx-api-migration-to-production-env
=> Fulcrum website connect to api.bzx.network

packages/fulcrum-website/_sass/_variables.scss, packages/fulcrum-website/_sass/component/_sections.scss
https://trello.com/c/Vzk1MXqK/79-fulcrum-fix-missing-hover-for-landing-page
=> Add hover for item blog

packages/fulcrum/src/services/FulcrumProvider.ts
ContractsSource didn't update on account activating from localStorage
=> Fix bug with updating contractsSource

packages/fulcrum-api/src/api/index.js, packages/fulcrum-api/src/fulcrum/index.js, packages/fulcrum-api/src/models/iTokenPrices.js, packages/fulcrum-api/src/models/pTokenPrices.js, packages/fulcrum-api/src/swagger.json
https://trello.com/c/5krXGlvi/66-api-for-ptokens-and-itokens-prices
=> bZx API edits

packages/fulcrum/src/components/LendForm.tsx, packages/fulcrum/src/styles/components/lend-form.mobile.scss, packages/fulcrum/src/styles/components/lend-form.scss
https://app.clubhouse.io/bzx1/story/130/notice-for-eth-lend-popup
=> Add notice for ETH lend popup

packages/fulcrum-website/_includes/footer.html
=> Remove litepaper in footer - fulcrum-website

packages/torque-website/_includes/footer.html
=> Remove litepaper link in footer - torque-website

packages/fulcrum/src/components/LendForm.tsx, packages/fulcrum/src/styles/components/lend-form.scss
https://app.clubhouse.io/bzx1/story/284/add-notice-for-unlend-screen-at-eth-pool
=> Add iETH to vBZRX notice to Unlend Form

packages/fulcrum/src/services/processors/ManageCollateralProcessor.ts, packages/fulcrum/src/services/processors/TradeBuyProcessor.ts, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/staking-dashboard/src/services/StakingProvider.ts, packages/torque/src/services/processors/BorrowProcessor.ts, packages/torque/src/services/processors/ExtendLoanProcessor.ts, packages/torque/src/services/processors/ManageCollateralProcessor.ts, packages/torque/src/services/processors/RepayLoanProcessor.ts, yarn.lock
=> Add waiting for token approval before sending other txns

packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/services/processors/LendChaiProcessor.ts, packages/fulcrum/src/services/processors/LendErcProcessor.ts, packages/fulcrum/src/services/processors/ManageCollateralProcessor.ts, packages/fulcrum/src/services/processors/TradeBuyProcessor.ts, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/staking-dashboard/src/services/StakingProvider.ts, packages/torque/src/services/TorqueProvider.ts, packages/torque/src/services/processors/BorrowProcessor.ts, packages/torque/src/services/processors/ExtendLoanProcessor.ts, packages/torque/src/services/processors/ManageCollateralProcessor.ts, packages/torque/src/services/processors/RepayLoanProcessor.ts
=> Update getLargeApprovalAmount method

packages/bzx-api/src/contracts/iTokenContract.js, packages/bzx-api/src/fulcrum/index.js, packages/bzx-api/src/torque/index.js
Fixes #257 
Fixes #253 
Fixes #240
=> bzx API: fix getBorrowEstimate endpoint for Torque

packages/fulcrum/src/components/HistoryTokenGrid.tsx, packages/fulcrum/src/components/HistoryTokenGridRow.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/ContractsSource.ts, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/services/processors/TradeSellProcessor.ts
=> Update profit and trade close amount for SHORTs

packages/fulcrum/src/components/OwnTokenGridRow.tsx, packages/fulcrum/src/components/ProfitTicker.tsx, packages/fulcrum/src/components/TradeTokenGridRow.tsx
=> Fulcrum updates

packages/staking-dashboard/src/services/StakingProvider.ts
=> Staking: fix gas amount

packages/fulcrum/src/components/TradeForm.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/services/processors/TradeSellProcessor.ts
https://app.clubhouse.io/bzx1/story/535/tradefrom-close-estimate-amount
=> Fix loan close estimate

packages/torque/src/components/BorrowedFundsListItem.tsx, packages/torque/src/styles/components/borrowed-funds-list.scss
https://app.clubhouse.io/bzx1/story/517/liquidation-price-indicator-on-torque
=> Added liquidation price to Torque 

packages/fulcrum/src/contracts/iTokenContract.ts, packages/protocol-explorer/src/contracts/iTokenContract.ts, packages/staking-dashboard/src/services/StakingProvider.ts, packages/torque/src/contracts/iTokenContract.ts
https://app.clubhouse.io/bzx1/story/655/update-kovan-token-addresses
https://app.clubhouse.io/bzx1/story/552/update-dapps-contract-wrappers
=> Update kovan assets and contract ABIs with typescript wrappers using abi-gen 

packages/fulcrum/src/pages/TradePage.tsx, packages/torque/src/services/TorqueProvider.ts
https://app.clubhouse.io/bzx1/story/524/update-liquidation-price-formula
=> Updated liquidation formula based on loanParams maintenance margin

packages/fulcrum/src/components/InputReceive.tsx, packages/fulcrum/src/components/TradeForm.tsx, packages/fulcrum/src/styles/base/_base.scss, packages/fulcrum/src/styles/components/trade-form.scss
https://app.clubhouse.io/bzx1/story/708/when-click-sell-zero-is-populated-as-amount
Button will be disabled until a value is set
=> feat(fulcrum): disable sell button on sell position dialog with 0 value 

packages/fulcrum/public/datafeeds/udf/dist/bundle.js, packages/fulcrum/public/datafeeds/udf/lib/history-provider.js, packages/fulcrum/public/datafeeds/udf/lib/udf-compatible-datafeed-base.js, packages/fulcrum/public/datafeeds/udf/src/history-provider.ts, packages/fulcrum/public/datafeeds/udf/src/udf-compatible-datafeed-base.ts, packages/fulcrum/src/components/TVChartContainer.tsx
https://app.clubhouse.io/bzx1/story/598/feat-add-daily-and-weekly-candles-to-chart
=> Add daily, weekly and monthly candles to tradingview

packages/fulcrum/src/components/ProviderMenu.tsx, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/services/processors/LendChaiProcessor.ts, packages/fulcrum/src/services/processors/LendErcProcessor.ts, packages/fulcrum/src/services/processors/ManageCollateralProcessor.ts, packages/fulcrum/src/services/processors/TradeBuyProcessor.ts, packages/protocol-explorer/src/components/ProviderMenu.tsx, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/protocol-explorer/src/services/processors/LiquidationProcessor.ts, packages/torque/src/components/ProviderMenu.tsx, packages/torque/src/services/TorqueProvider.ts, packages/torque/src/services/processors/BorrowProcessor.ts, packages/torque/src/services/processors/ExtendLoanProcessor.ts, packages/torque/src/services/processors/ManageCollateralProcessor.ts, packages/torque/src/services/processors/RepayLoanProcessor.ts
https://app.clubhouse.io/bzx1/story/583/usdt-spend-limit-issue
=> fix(approval): Set approve to 0 before increase spend limit for USDT.

packages/protocol-explorer/src/components/AssetSelector.tsx, packages/protocol-explorer/src/components/LoanRow.tsx, packages/protocol-explorer/src/components/StatsChart.tsx, packages/protocol-explorer/src/pages/LiquidationsPage.tsx, packages/protocol-explorer/src/services/ExplorerProvider.ts
https://app.clubhouse.io/bzx1/story/594/explorer-improve-perfomance
=> Improve Explorer perfomance (liquidations page in particular)

packages/fulcrum/src/components/InnerOwnTokenGridRow.tsx, packages/fulcrum/src/components/TradeTokenGridRow.tsx, packages/fulcrum/src/components/TradeTxLoaderStep.tsx, packages/fulcrum/src/domain/IBorrowedFundsState.ts, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/services/processors/TradeSellProcessor.ts
https://app.clubhouse.io/bzx1/story/824/improve-fulcrum-trade-page-perfomance
=> Improve Fulcrum trade page performance 

packages/torque/src/components/BorrowForm.tsx
https://app.clubhouse.io/bzx1/story/947/borrow-default-initial-collaterization-bug
=> Fix default initial collaterization percent on collateral change

packages/fulcrum/src/components/AppRouter.tsx, packages/fulcrum/src/components/LendTokenSelector.tsx, packages/fulcrum/src/components/LendTokenSelectorItem.tsx, packages/fulcrum/src/components/OnChainIndicator.tsx, packages/fulcrum/src/domain/ProviderTypeDictionary.ts, packages/fulcrum/src/domain/Web3ConnectionFactory.ts, packages/fulcrum/src/layout/HeaderOps.tsx, packages/fulcrum/src/pages/LendPage.tsx, packages/fulcrum/src/pages/StatsPage.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/ContractsSource.ts, packages/fulcrum/src/services/FulcrumProvider.ts, packages/fulcrum/src/styles/components/lend-token-selector.scss
https://app.clubhouse.io/bzx1/story/848/improve-fulcrum-lend-page-perfomance
=> Update Lend Page perfomance. Update wallet connection changing

.gitignore, packages/bzx-api/.eslintrc, packages/bzx-api/package-lock.json, packages/bzx-api/package.json, packages/bzx-api/readme.md, packages/bzx-api/src/fulcrum/index.js, packages/fulcrum/src/services/FulcrumProvider.ts
Here is my attempt at including vbzrx in our calculation of the TVL.
What I am unsure of, is if I needed to also update the total supply in the way I did it. 
https://app.clubhouse.io/bzx1/story/532/update-tvl-calculation-for-the-explorer
=> feat(backend-api): include vbzrx amounts for TVL

packages/bzx-api/src/fulcrum/index.js
=> yield decrease

packages/protocol-explorer/src/components/LiquidationForm.tsx, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/protocol-explorer/src/styles/components/_buttons.scss, packages/protocol-explorer/src/styles/components/_liquidation-form.scss
https://app.clubhouse.io/bzx1/story/1082/consider-user-wallet-balance
=> Add warnings to Liquidation form about insufficient wallet balance

packages/fulcrum/src/components/LendForm.tsx, packages/fulcrum/src/components/LendTokenSelectorItem.tsx
https://app.clubhouse.io/bzx1/story/1091/fulcrum-lend-numbers
=> Fulcrum LEND Numbers

packages/fulcrum/src/components/DropdownSelect.tsx, packages/fulcrum/src/components/HistoryTokenGridRow.tsx, packages/fulcrum/src/components/OwnTokenGridRow.tsx
https://app.clubhouse.io/bzx1/story/1051/trading-pair-naming
=> Trading pair naming

packages/torque/src/components/ExtendLoanForm.tsx, packages/torque/src/components/InputAmount.tsx, packages/torque/src/components/RepayLoanForm.tsx, packages/torque/src/styles/components/button.scss, packages/torque/src/styles/components/input-amount.scss, packages/torque/src/styles/components/repay-loan-form.scss
https://app.clubhouse.io/bzx1/story/1042/trying-to-repay-loan-it-proposes-to-close-in-full-100-while-my-wallet-doesnt-hold-that-much
=> Torque: Restrict repay amount with max user's balance

packages/torque/src/components/AssetSelector.tsx, packages/torque/src/components/BorrowForm.tsx, packages/torque/src/services/TorqueProvider.ts, packages/torque/src/styles/components/button.scss
https://app.clubhouse.io/bzx1/story/1002/lend-still-available-for-borrowing
=> Torque: restrict max borrow amount, disable LEND token borrowing

packages/torque/src/components/BorrowMoreForm.tsx, packages/torque/src/styles/components/borrow-more-form.scss
https://app.clubhouse.io/bzx1/story/1097/insufficient-collateral-error-ui-estimating-collateral-ratio-incorrectly
=> Torque: Do not allow to submit borrow more form with "Enter"

packages/fulcrum/src/domain/WalletConnectors.ts, packages/fulcrum/src/domain/Web3ConnectionFactory.ts, packages/fulcrum/src/services/FulcrumProvider.ts, packages/protocol-explorer/src/domain/WalletConnectors.ts, packages/protocol-explorer/src/domain/Web3ConnectionFactory.ts, packages/protocol-explorer/src/pages/LiquidationsPage.tsx, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/staking-dashboard/src/domain/WalletConnectors.ts, packages/staking-dashboard/src/domain/Web3ConnectionFactory.ts, packages/staking-dashboard/src/services/StakingProvider.ts, packages/torque/src/components/BorrowedFundsListItem.tsx, packages/torque/src/domain/WalletConnectors.ts, packages/torque/src/domain/Web3ConnectionFactory.ts, packages/torque/src/services/TorqueProvider.ts
https://app.clubhouse.io/bzx1/story/1211/use-rpcsubprovider-for-data-fetching-instead-of-alchemysubprovider
=> Use 0x RPCSubprovider for data fetching instead of AlchemySubprovider

packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/FulcrumProvider.ts
https://app.clubhouse.io/bzx1/story/1260/positions-seems-to-be-not-appeared-from-the-first-render
=> Fulcrum: fetch user positions with retries. 

packages/fulcrum/src/pages/LendPage.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/styles/base/_base.scss, packages/torque/src/pages/BorrowPage.tsx
https://app.clubhouse.io/bzx1/story/1227/bug-dapp-fetches-data-when-on-the-wrong-network
=> Add message about wrong network

packages/fulcrum/src/components/ProviderMenuListItem.tsx, packages/protocol-explorer/src/components/ProviderMenuListItem.tsx, packages/torque/src/components/ProviderMenuListItem.tsx
https://app.clubhouse.io/bzx1/story/1300/collect-metrics-about-wallet-providers
=> Collect metrics about wallet providers

packages/bzx-api/package.json, packages/bzx-api/src/api/index.js, packages/bzx-api/src/config.json, packages/bzx-api/src/config/iTokens.js, packages/bzx-api/src/contracts/iBZxContract.js, packages/bzx-api/src/contracts/iTokenContract.js, packages/bzx-api/src/fulcrum/index.js, packages/bzx-api/src/models/loanParams.js, packages/bzx-api/src/models/loansParams.js, packages/bzx-api/src/swagger.json, packages/protocol-explorer/package.json, packages/protocol-explorer/src/components/AppRouter.tsx, packages/protocol-explorer/src/components/CopyToClipboard.tsx, packages/protocol-explorer/src/components/LoanRow.tsx, packages/protocol-explorer/src/components/ParamGrid.tsx, packages/protocol-explorer/src/components/ParamRow.tsx, packages/protocol-explorer/src/components/PlatformTabs.tsx, packages/protocol-explorer/src/components/Search.tsx, packages/protocol-explorer/src/contracts/iBZxContract.ts, packages/protocol-explorer/src/domain/Platform.ts, packages/protocol-explorer/src/layout/HeaderMenu.tsx, packages/protocol-explorer/src/pages/LoanParamsPage.tsx, packages/protocol-explorer/src/services/ExplorerProvider.ts, packages/protocol-explorer/src/styles/components/_clipboard.scss, packages/protocol-explorer/src/styles/components/_table.scss, packages/protocol-explorer/src/styles/components/_tabs.scss, packages/protocol-explorer/src/styles/index.scss
Need to update backend API. 
Get data from new endpoint /loans-params.
=> Add page with protocol loan params 

packages/fulcrum/src/components/StatsTokenGrid.tsx, packages/fulcrum/src/components/StatsTokenGridHeader.tsx, packages/fulcrum/src/components/StatsTokenGridRow.tsx, packages/fulcrum/src/components/TradeTokenGridHeader.tsx, packages/fulcrum/src/components/TradeTokenGridRow.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/styles/components/trade-token-grid.scss, packages/torque/src/components/AssetSelector.tsx, packages/torque/src/components/AssetSelectorItem.tsx
https://app.clubhouse.io/bzx1/story/1373/remove-yield-apr-labels
=> Remove Yield APR from Torque and Fulcrum

packages/torque/src/components/BorrowForm.tsx
https://app.clubhouse.io/bzx1/story/1361/torque-borrow-shouldn-t-be-restricted-with-max-300-collateralization
=> Torque: increase max available collaterization percent

packages/torque/src/layout/HeaderOps.tsx
https://app.clubhouse.io/bzx1/stories/space/51/everything
=> Torque: Update header navigation links

packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/FulcrumProvider.ts
https://app.clubhouse.io/bzx1/story/1420/add-yfi-trading-pairs
=> Fulcrum: Add YFI/* trading pairs

packages/fulcrum-website/_includes/header.html, packages/fulcrum-website/assets/js/main.js
https://app.clubhouse.io/bzx1/story/1419/app-button-fulcrum-lend-landing-page
=> Update link in the header

packages/fulcrum/src/components/LendForm.tsx
https://app.clubhouse.io/bzx1/story/1478/remove-lend-dai-with-chai
=> Hide the drop-down with Chai

packages/fulcrum/src/components/InnerOwnTokenGrid.tsx, packages/fulcrum/src/components/InnerOwnTokenGridHeader.tsx, packages/fulcrum/src/components/InnerOwnTokenGridRow.tsx, packages/fulcrum/src/components/OwnTokenGridHeader.tsx, packages/fulcrum/src/components/OwnTokenGridRow.tsx, packages/fulcrum/src/components/TradeTokenGrid.tsx, packages/fulcrum/src/components/TradeTokenGridHeader.tsx, packages/fulcrum/src/styles/components/inner-own-token-grid.scss, packages/fulcrum/src/styles/components/own-token-grid.scss, packages/fulcrum/src/styles/components/tooltip.scss
https://app.clubhouse.io/bzx1/story/1445/tooltip-for-mid-market-price
https://app.clubhouse.io/bzx1/story/1462/new-profit-display-tooltip
https://app.clubhouse.io/bzx1/story/1463/change-tooltip-text-add-one
=> Fulcrum: Update tooltips

packages/staking-dashboard/src/App/Staking/Governance/Governance.tsx, packages/staking-dashboard/src/App/Staking/Governance/GovernanceItem.tsx, packages/staking-dashboard/src/App/Staking/Governance/GovernanceVM.ts, packages/staking-dashboard/src/App/Staking/Staking.tsx, packages/staking-dashboard/src/styles/components/_governance.scss, packages/staking-dashboard/src/ui-framework/styles/layout/layout-self.scss
https://app.clubhouse.io/bzx1/story/1358/governance-page
=> Staking: Add Proposals explorer tab

packages/fulcrum/src/components/ManageCollateralForm.tsx, packages/fulcrum/src/components/OwnTokenGrid.tsx, packages/fulcrum/src/pages/TradePage.tsx, packages/fulcrum/src/services/FulcrumProvider.ts, packages/torque/src/components/BorrowForm.tsx, packages/torque/src/components/ManageCollateralFormWeb3.tsx, packages/torque/src/services/TorqueProvider.ts, packages/torque/src/styles/components/manage-collateral-form.scss
https://app.clubhouse.io/bzx1/story/1467/collateral-100-max-fix
=> Сollateral max fix
